[build]
  command = "npm run build"
  publish = "dist"
# Permite incluir imágenes externas en el CDN de Netlify
[images]
  remote_images = ["http://panel.camiñosfaladosdarua.gal/.*", "http://panel.cami%C3%B1osfaladosdarua.gal/.*"]